# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_accuracy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='M1_Train_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(choices=[(11, '서울'), (26, '부산'), (27, '대구'), (29, '인천'), (30, '대전'), (31, '울산'), (36, '세종'), (41, '경기도'), (42, '강원도'), (43, '충북'), (44, '충남'), (45, '전북'), (46, '전남'), (47, '경북'), (48, '경남'), (49, '제주')], default='서울', max_length=20)),
                ('triglycerides', models.FloatField(blank=True, null=True)),
                ('hdl', models.FloatField(blank=True, null=True)),
                ('ldl', models.FloatField(blank=True, null=True)),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, '남'), (2, '여')], default='남')),
                ('waist', models.FloatField(blank=True, null=True)),
                ('systolic_pressure', models.FloatField(blank=True, null=True)),
                ('diastolic_pressure', models.FloatField(blank=True, null=True)),
                ('fbs', models.FloatField(blank=True, null=True)),
                ('old', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('smoke', models.PositiveSmallIntegerField(choices=[(1, '비흡연'), (2, '금연'), (3, '흡연')], default='금연')),
                ('alcohol_hepatitis', models.PositiveSmallIntegerField(choices=[(1, '알콜성 간염'), (2, '정상')], default='정상')),
            ],
        ),
        migrations.DeleteModel(
            name='Accuracy_Data',
        ),
    ]
